registry = 'cbolt'
name = 'passenger-ruby22'
version = 'latest'

task default: %w(build push)

task :build do
  sh "docker build -t #{registry}/#{name}:#{version} ."
end

task :push do
  sh "docker push #{registry}/#{name}:#{version}"
end
